from path_in_IT_bot.factories.abstract_factory import AbstractFactory as AbstractFactory
from path_in_IT_bot.readers.model_reader import TelegramBotProducer as TelegramBotProducer, TelegramBotProduct as TelegramBotProduct, model as model

class ProducersFactory(AbstractFactory):
    def __init__(self) -> None: ...
    @property
    def items(self): ...

class Producer:
    def __init__(self, name: str, producer_model: TelegramBotProducer) -> None: ...
    @property
    def name(self): ...
    @property
    def currency(self) -> str: ...
    @property
    def wellcome_message(self): ...
    @property
    def translate(self): ...
    @property
    def products(self) -> dict[str, TelegramBotProduct]: ...
