from aiogram.fsm.state import StatesGroup
from typing import Iterable, Type

class StatesGroupBuilder:
    def __init__(self, *states: Iterable[str]) -> None: ...
    def add(self, *states) -> None: ...
    def build(self) -> Type[StatesGroup]: ...
